name: Publish to Registry
on:
  push:
    branches:
      - master
 jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: cargauer/hello-github-actions@master
      with:
        name: cargauer/hga/hello
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
